### ISSUE TITLE
Up-call in get object size code

### ISSUE THREAD

**Issue by wenyuzhao** [mmtk/mmtk-openjdk#63]
Currently, we call into OpenJDK to get object size before each object copy:

https://github.com/mmtk/mmtk-openjdk/blob/master/mmtk/src/object_model.rs#L22

Considering the large number of heap objects, this can slow down the performance quite a lot.

There are two potential approaches to solve this performance issue:

1. Rewrite object size calculation code in rust to reduce this cross-language call.
2. Create a bulk-copy work packet and let VM handle this completely.

I suggest the second approach. V8 binding can benefit from this as well -- its object scanning and size calculation code are too complex to port.

**Comment by qinsoon** [comment]
This can be closed. Approach 1 is done in https://github.com/mmtk/mmtk-openjdk/pull/130.
